[package]
name = "keron-cli"
version = "0.0.1"
edition.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
clap = { workspace = true }
minus = { workspace = true }
thiserror = { workspace = true }
keron-engine = { path = "../keron-engine" }
keron-report = { path = "../keron-report" }
keron-source = { path = "../keron-source" }
